version: '3'
services:
  database:
    image: redis:6.2
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes: 
      - .:/data
  app:
    container_name: sdu_student_grade_tracker
    image: sdu_student_grade_tracker
    depends_on:
      - database
    ports:
      - 3000:3000
    links:
      - database
    volumes:
      - .:/sdu_student_grade_tracker
      
volumes:
  database:
    driver: local
  app:
    driver: local
